public static class SceneBuildIndex
{
    public static readonly System.Collections.Generic.Dictionary<string, int> SceneIndex = new System.Collections.Generic.Dictionary<string, int>()
    {
        {"StartScene", 0},
        {"SplashScene", 1},
        {"DownloadScene", 2},
        {"LoginBonusScene", 3},
        {"Footer", 4},
        {"Header", 5},
        {"HomeScene", 6},
        {"Mission", 7},
        {"StoryScene", 8},
        {"CardScene", 9},
        {"EvolutionAnimationScene", 10},
        {"CardEnhancementScene", 11},
        {"CardEvolutionScene", 12},
        {"CardScene_Deck", 13},
        {"CardListScene", 14},
        {"ItemListScene", 15},
        {"RoomScene", 16},
        {"ClubActivityScene", 17},
        {"StoryAlbumScene", 18},
        {"AccessoryScene", 19},
        {"GachaScene", 20},
        {"GachaAnimation", 21},
        {"GachaResult", 22},
        {"ShopScene", 23},
        {"ShopAccountingItemScene", 24},
        {"ShopIABItemScene", 25},
        {"MenuScene", 26},
        {"BattleDeckSelectDummyScene", 27},
        {"BattleResultWinDummyScene", 28},
        {"BattleMainScene", 29},
        {"BattleResultLoseDummyScene", 30},
        {"BattleNetworkStartScene", 31},
        {"BattlePrepareScene", 32},
        {"BattleResult", 33},
        {"FriendScene", 34},
        {"DevtoolsScene", 35},
        {"BraveSystemScene", 36},
        {"DebugBattleStoryScene", 37},
    };
}
